# Generated by Django 5.2.6 on 2025-09-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_name', models.CharField(max_length=20)),
                ('car_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=20)),
                ('date_of_purchase', models.DateTimeField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
